sudo: false
branches:
  only:
    - master
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: PATH="./bats/bin:$PATH" test/run
language: c
env:
  - NODENV_NATIVE_EXT=
  - NODENV_NATIVE_EXT=1
