on: gollum

permissions: { issues: write }
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: >
          gh issue new --label wiki -R "$GITHUB_REPOSITORY"
          -t "$TITLE" -b "$BODY"
        env:
          GH_TOKEN: ${{ github.token }}
          TITLE: "wiki edit by @${{ github.event.sender.login }}"
          BODY: |
            ${{ toJson(github.event.pages) }}

            ${{ join(github.event.pages.*.html_url) }}
